app/books/models.py
#-*-coding: utf-8-*-
from app import db

class Book(db.Model):
    
    __tablename__ = 'books_book'
    
    id = db.Column(
        db.Integer, 
        primary_key=True)
    
    name = db.Column(
        db.String(255))
    
    def __init__(self, name):
        self.name = name
    
    def __repr__(self):
        return u'<Book {0}>'.format(self.id)
    

app/books/forms.py
#-*-coding: utf-8 -*-
from flask_wtf import Form
from wtforms import StringField, HiddenField
from wtforms.ext.sqlalchemy.fields import QuerySelectMultipleField 
from wtforms.validators import DataRequired
from app.authors.models import Author

REQUIRED_MESSAGE = u"Поле обязательно для заполнения"

class BookForm(Form):
    id = HiddenField()
    
    name = StringField(
        label=u'Название', validators=[DataRequired(message=REQUIRED_MESSAGE)])
    
    authors = QuerySelectMultipleField(
        label=u'Авторы',
        query_factory=lambda: Author.query.all(),
        get_label=lambda a: a.name,
        validators=[])

app/books/views.py
#-*-coding: utf-8 -*-
from flask import (Blueprint, render_template, request, jsonify, url_for)
from app import db
from app.views import BaseTableView

from app.books.models import Book
from app.books.forms import BookForm

mod = Blueprint('books', 
                __name__, 
                url_prefix='/books', 
                template_folder='templates')

@mod.route('/')
def book_list():
    return render_template("books/book_list.html")

@mod.route('/book_table/')
def book_table():
    table_view = BookTableView()
    return table_view.render_to_response()

class BookTableView(BaseTableView):
    model = Book
    
    columns_map = {
        '0': 'id',
        '1': 'name',
    }

def render_form(form, path):
    context = {
        'form': form,
        'path': path
    }
    form_html = render_template('books/_add_form.html', **context)
    return form_html

@mod.route('/get_add_form/')
def get_add_form():
    form = BookForm()
    path = url_for('books.add_book')
    return render_form(form, path)
    
@mod.route('/add_book/', methods=['POST'])
def add_book():
    form = BookForm(request.form)
    if form.validate_on_submit():
        book = Book(name=form.name.data)
        book.authors.extend(form.authors.data)
        db.session.add(book)
        db.session.commit()
        return jsonify({'status': 'success'})
    
    path = url_for('books.add_book')
    return jsonify({'status': 'fail', 'form_html':render_form(form, path)})        

@mod.route('/book_info/')
def book_info():
    book_id = int(request.args.get('item_id'))
    book = Book.query.get(book_id)
    context = {'book': book}
    return render_template('books/book_info.html', **context)
    
@mod.route('/remove_book/', methods=['POST'])
def remove_book():
    book_id = int(request.form.get('item_id'))
    book = Book.query.get(book_id)
    db.session.delete(book)
    db.session.commit()
    return ''

@mod.route('/get_edit_form/')
def get_edit_form():
    item_id = int(request.args.get('item_id'))
    book = Book.query.get(item_id)
    form = BookForm(obj=book)
    path = url_for('books.edit_book')
    return render_form(form, path)

@mod.route('/edit_book/', methods=['POST'])
def edit_book():
    book_id = request.form.get('id')
    book = Book.query.get(book_id)
    form = BookForm(request.form, obj=book)
    if form.validate_on_submit():
        form.populate_obj(book)
        db.session.commit()
        return jsonify({'status': 'success'})
    
    path = url_for('books.edit_book')
    return jsonify({'status': 'fail', 'form_html':render_form(form, path)})        
    
    
    

    
    
    

app/books/templates/books/_add_form.html
<form class="item_form" method='post' action="{{ path }}">
	{{ form.hidden_tag() }}
	<div class="form_row">
		<label>{{ form.name.label.text }}<span class="required">*</span>:</label>
		{{ form.name(class="form-control") }}
		{% if form.name.errors %}
        <ul class="errors">
        	{% for error in form.name.errors %}
        	<li>{{ error }}</li>
        	{% endfor %}
        </ul>
    	{% endif %}
	</div>
	
	<div class="form_row">
		<label>{{ form.authors.label.text }}:</label>
		{{ form.authors(class="form-control") }}
		{% if form.authors.errors %}
        <ul class="errors">
        	{% for error in form.authors.errors %}
        	<li>{{ error }}</li>
        	{% endfor %}
        </ul>
    	{% endif %}
	</div>
</form>

app/books/templates/books/book_info.html
<h3>
	{{ book.name }}
</h3>
<h5>
	Авторы: 
	{% for a in book.authors %}
	{{ a.name }}{% if not loop.last %},{% endif %}
	{% endfor %}
</h5>

app/books/templates/books/book_list.html
{% extends 'base.html' %}

{% block title %}
	{{ _('Book list') }}
{% endblock %}

{% block tabs %}
	<li class="active">
	   <a>{{ _('Book list') }}</a>
	</li>
	<li>
	   <a href="{{ url_for('authors.author_list') }}">{{ _('Author list') }}</a>
	</li>
{% endblock %}

{% block scripts %}
	{{ super() }}
	<script type="text/javascript">
		var book_table_path = "{{ url_for('books.book_table') }}";
		var book_form_path = "{{ url_for('books.get_add_form') }}";
		var book_add_path = "{{ url_for('books.add_book') }}";
		var book_info_path = "{{ url_for('books.book_info') }}";
		var book_remove_path = "{{ url_for('books.remove_book') }}";
		var book_edit_form_path = "{{ url_for('books.get_edit_form') }}";
		var book_edit_path = "{{ url_for('books.edit_book') }}";
	</script>
	<script src="/static/js/books.js" type="text/javascript"></script>
{% endblock %}

{% block content %}
	<div id="books">
		<table class="list_table table table-striped table-bordered table-hover">
		    <thead>
		        <tr>
		            <th class="id_col">ID</th>
		            <th>{{ _('Title') }}</th>
		            <th class="actions_col">{{ _('Actions') }}</th>
		        </tr>
		    </thead>
		</table>
	</div>
{% endblock %}