app/authors/models.py
#-*-coding: utf-8-*-
from app import db

author_books = db.Table(
    'authors_books',
    db.Column('author_id', db.Integer, db.ForeignKey('authors_author.id')),
    db.Column('book_id', db.Integer, db.ForeignKey('books_book.id')))

class Author(db.Model):
    
    __tablename__ = 'authors_author'
    
    id = db.Column(
        db.Integer, 
        primary_key=True)
    
    name = db.Column(
        db.String(255))
    
    books = db.relationship('books.models.Book', secondary=author_books,
        backref=db.backref('authors', lazy='dynamic'))
    
    def __init__(self, name):
        self.name = name
    
    def __repr__(self):
        return u'<Author {0}>'.format(self.name)    
    

app/authors/views.py
#-*-coding: utf-8 -*-
from flask import (Blueprint, render_template, request, jsonify, url_for)
from app import db
from app.views import BaseTableView

from app.authors.models import Author
from app.authors.forms import AuthorForm

mod = Blueprint('authors', 
                __name__, 
                url_prefix='/authors', 
                template_folder='templates')

@mod.route('/')
def author_list():
    return render_template("authors/author_list.html")

@mod.route('/author_table/')
def author_table():
    table_view = AuthorTableView()
    return table_view.render_to_response()

class AuthorTableView(BaseTableView):
    model = Author
    
    columns_map = {
        '0': 'id',
        '1': 'name',
    }

def render_form(form, path):
    context = {
        'form': form,
        'path': path
    }
    form_html = render_template('authors/_add_form.html', **context)
    return form_html

@mod.route('/get_add_form/')
def get_add_form():
    form = AuthorForm()
    path = url_for('authors.add_author')
    return render_form(form, path)
    
@mod.route('/add_author/', methods=['POST'])
def add_author():
    form = AuthorForm(request.form)
    if form.validate_on_submit():
        author = Author(name=form.name.data)
        author.books.extend(form.books.data)
        db.session.add(author)
        db.session.commit()
        return jsonify({'status': 'success'})
    
    path = url_for('authors.add_author')
    return jsonify({'status': 'fail', 'form_html':render_form(form, path)})        

@mod.route('/author_info/')
def author_info():
    author_id = int(request.args.get('item_id'))
    author = Author.query.get(author_id)
    context = {'author': author}
    return render_template('authors/author_info.html', **context)
    
@mod.route('/remove_author/', methods=['POST'])
def remove_author():
    author_id = int(request.form.get('item_id'))
    author = Author.query.get(author_id)
    db.session.delete(author)
    db.session.commit()
    return ''

@mod.route('/get_edit_form/')
def get_edit_form():
    item_id = int(request.args.get('item_id'))
    book = Author.query.get(item_id)
    form = AuthorForm(obj=book)
    path = url_for('authors.edit_author')
    return render_form(form, path)

@mod.route('/edit_author/', methods=['POST'])
def edit_author():
    book_id = request.form.get('id')
    book = Author.query.get(book_id)
    form = AuthorForm(request.form, obj=book)
    if form.validate_on_submit():
        form.populate_obj(book)
        db.session.commit()
        return jsonify({'status': 'success'})
    
    path = url_for('author.edit_book')
    return jsonify({'status': 'fail', 'form_html':render_form(form, path)})        
    
    
    

    
    
    

app/authors/templates/authors/_add_form.html
<form class="item_form" method='post' action="{{ path }}">
	{{ form.hidden_tag() }}
	<div class="form_row">
		<label>{{ form.name.label.text }}<span class="required">*</span>:</label>
		{{ form.name(class="form-control") }}
		{% if form.name.errors %}
        <ul class="errors">
        	{% for error in form.name.errors %}
        	<li>{{ error }}</li>
        	{% endfor %}
        </ul>
    	{% endif %}
	</div>
	
	<div class="form_row">
		<label>{{ form.books.label.text }}:</label>
		{{ form.books(class="form-control") }}
		{% if form.books.errors %}
        <ul class="errors">
        	{% for error in form.books.errors %}
        	<li>{{ error }}</li>
        	{% endfor %}
        </ul>
    	{% endif %}
	</div>
</form>

app/authors/templates/authors/author_info.html
<h3>
	{{ author.name }}
</h3>
<h5>
	Книги: 
	{% for b in author.books %}
	{{ b.name }}{% if not loop.last %},{% endif %}
	{% endfor %}
</h5>

app/authors/templates/authors/author_list.html
{% extends 'base.html' %}

{% block title %}
	{{ _('Author list') }}
{% endblock %}

{% block tabs %}
	<li>
	   <a href="{{ url_for('books.book_list') }}">{{ _('Book list') }}</a>
	</li>
	<li class="active">
	   <a>{{ _('Author list') }}</a>
	</li>
{% endblock %}

{% block scripts %}
	{{ super() }}
	<script type="text/javascript">
		var author_table_path = "{{ url_for('authors.author_table') }}";
		var author_form_path = "{{ url_for('authors.get_add_form') }}";
		var author_add_path = "{{ url_for('authors.add_author') }}";
		var author_info_path = "{{ url_for('authors.author_info') }}";
		var author_remove_path = "{{ url_for('authors.remove_author') }}";
		var author_edit_form_path = "{{ url_for('authors.get_edit_form') }}";
		var author_edit_path = "{{ url_for('authors.edit_author') }}";
	</script>
	<script src="/static/js/authors.js" type="text/javascript"></script>
{% endblock %}

{% block content %}
	<div id="authors">
		<table class="list_table table table-striped table-bordered table-hover">
		    <thead>
		        <tr>
		            <th class="id_col">ID</th>
		            <th>{{ _('Title') }}</th>
		            <th class="actions_col">{{ _('Actions') }}</th>
		        </tr>
		    </thead>
		</table>
	</div>
{% endblock %}